SRC += i2c_master.c

# Debug
# CONSOLE_ENABLE = yes
# COMMAND_ENABLE = yes

# Settings
SERIAL_DRIVER = vendor
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
VIA_ENABLE = no

# Pimoroni PIM447
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
PIMORONI_TRACKBALL_ADDRESS = 0x0A
PIMORONI_TRACKBALL_TIMEOUT = 100
PIMORONI_TRACKBALL_SCALE = 3
PIMORONI_TRACKBALL_DEBOUNCE_CYCLES = 20
PIMORONI_TRACKBALL_ERROR_COUNT = 10

# OLED
OLED_ENABLE = yes
OLED_DRIVER = SSD1306