# Debug
# CONSOLE_ENABLE = yes
# COMMAND_ENABLE = yes

# Settings
# SERIAL_DRIVER = vendor
# MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
VIA_ENABLE = yes
EXTRAKEY_ENABLE = yes
OS_DETECTION_ENABLE = yes
COMBO_ENABLE = yes

# Settings for Diet Firmware Size
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no

# Pimoroni PIM447
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = pimoroni_trackball
# PIMORONI_TRACKBALL_ADDRESS = 0x0A
# PIMORONI_TRACKBALL_TIMEOUT = 100
# PIMORONI_TRACKBALL_SCALE = 3
# PIMORONI_TRACKBALL_DEBOUNCE_CYCLES = 20
# PIMORONI_TRACKBALL_ERROR_COUNT = 10

# OLED
# OLED_ENABLE = yes
# OLED_DRIVER = ssd1306

# RGB
RGBLIGHT_ENABLE = yes
